## Functions

We would like to write a piece of code that computes the factorial of a number, returns the output, and that can be used in any place we want... That is: we write a *function* with some appropriate name (what about to name it *factorial*?)

In [1]:
def factorial(n):     
    jn=1
    fact=1
    while jn <= n:
        fact=fact*jn
        jn=jn+1
        
    return fact

Basic syntax of a function definition:

- The keyword **def** is used to define a function;
- *def* is followed by the **name** we choose for the function; 
- the name of the function must always be followed by parentheses; inside such parentheses there are the **arguments** to the function; if a function does not require arguments, nothing will appear between those parentheses...
- Then the **body** of the function will follow (*indented*); the *body* is the set of instructions that must be executed by the function itself.
- If the function has to return one or more values, a **return** instruction must be present, followed by the list of values to be returned.

#### Test our function immediately...

We *call* the function with an appropriate argument...

In [2]:
factorial(5)

120

... or something like that:

In [3]:
n_list=[1,2,3,4,5,6,7]

print("n n!\n")
for il in n_list:
    print(il, factorial(il))

n n!

1 1
2 2
3 6
4 24
5 120
6 720
7 5040


Note that the variables defined *inside* the body of the function are *lost* when the function exits:

In [4]:
print(fact)

NameError: name 'fact' is not defined

even if the *value* of *fact* is *returned* by the function. The same is true for the variables *jn* and *n* (the latter being the argument to the function). *Much more on this later!*

However, we could save the result of the function in a variable:

In [5]:
fact=factorial(7)
print(fact)

5040


#### keyword arguments

We might want to use the function so that 

- it prints out explicitly the result, or 
- we just want a number that can possibly be saved in a variable; 
- moreover we want that if the result is printed (by a *print* function) no number should be returned

We use a *keyword argument* (*prn* in our case) for which a default value is defined

In [6]:
def factorial(n, prn=False):     
    jn=1
    fact=1
    while jn <= n:
        fact=fact*jn
        jn=jn+1
        
    if prn:
       print("The factorial of the number %3i  is %6i" % (n, fact))
    else:
       return fact

In [7]:
factorial(5, prn=True)

The factorial of the number   5  is    120


... but

In [8]:
factorial(5)

120

Note that in the case *prn* is True, no *return* instruction is executed and, therefore, the function *factorial* does return nothing (it returns *None*). Indeed:

In [9]:
r_fact=factorial(5, prn=True)
print("\nType and value of the variable r_fact: ", type(r_fact), r_fact)

The factorial of the number   5  is    120

Type and value of the variable r_fact:  <class 'NoneType'> None


### Documenting the function... 

Always take your time to *document* the function!

In [10]:
def factorial(n, prn=False):   
    '''
    Computes the factorial of a number
    
    Args:
        n:   number whose factorial has to be computed
        
    kargs:
        prn: if True, result is printed (default False)
        
    Returns:
        factorial of the number n
           
    Note: 
        if prn is True, no value will be returned 
    '''
    jn=1
    fact=1
    while jn <= n:
        fact=fact*jn
        jn=jn+1
        
    if prn:
       print("The factorial of the number %3i  is %6i" % (n, fact))
    else:
       return fact

Documentation will be printed by using the *help* function

In [11]:
help(factorial)

Help on function factorial in module __main__:

factorial(n, prn=False)
    Computes the factorial of a number

    Args:
        n:   number whose factorial has to be computed

    kargs:
        prn: if True, result is printed (default False)

    Returns:
        factorial of the number n

    Note:
        if prn is True, no value will be returned



### Checking your argument *n*

Check to limit the possible errors (at least *usage errors*)

In [12]:
def factorial(n, prn=False):   
    '''
    Computes the factorial of a number
    
    Args:
        n:   number whose factorial has to be computed
        
    kargs:
        prn: if True, result is printed (default False)
        
    Returns:
        factorial of the number n
           
    Note: 
        if prn is True, no value will be returned 
    '''
    if type(n) != int:
        print("Non integer argument")
        return
    if n < 0:
        print("Negative argument")
        return
    
    if n == 0:
       fact=1
       if prn:
          print("The factorial of the number %3i  is %6i" % (n, fact))
          return
       else:
          return fact 
        
    jn=1
    fact=1
    while jn <= n:
        fact=fact*jn
        jn=jn+1
        
    if prn:
       print("The factorial of the number %3i  is %6i" % (n, fact))
    else:
       return fact

In [13]:
factorial(6, prn=True)

The factorial of the number   6  is    720


In [14]:
factorial(-3, prn=True)

Negative argument


## Recursion...

The idea is the following: a *function that calls itself* until some condition is verified... 

In [15]:
def recursive(n):
    print(n, end=" ")
    n=n-1
    if n >= 0:
       recursive(n)

In [16]:
recursive(12)

12 11 10 9 8 7 6 5 4 3 2 1 0 

### A little bit complicated factorial function (using recursion)

It is just an example where *recursion* is used...

A *class* is defined (much more on this later...) 

In [17]:
# Class definition

class Factorial():

    @classmethod
    def set_fact(cls, fact):
        cls.fact=fact

    @classmethod
    def compute(cls, n, prn=False):
        cls.set_fact(1)
        cls.fact_rec(n)
        if prn:
           print("The factorial of %3i  is %6i" % (n, cls.fact))
        else:
           return cls.fact

    @classmethod
    def fact_rec(cls, b):            # <--- recursive function
        cls.fact=b*cls.fact
        b=b-1
        if b == 1:
           return 
        else:
           cls.fact_rec(b)
    

Let's use it!

In [18]:
Factorial.compute(10, prn=True)

The factorial of  10  is 3628800


The older (not recursive) definition of the factorial function returns (hopefully) the same value:

In [19]:
factorial(10, prn=True)

The factorial of the number  10  is 3628800


What is the *best* function (at least in term of *efficiency*)? Use the *timeit* Python function:

In [20]:
timeit(factorial(100))

7.67 μs ± 157 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [21]:
timeit(Factorial.compute(100))

32.2 μs ± 1.77 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In this case the *non-recursive* function is more efficient.

### Optimizing functions (Advanced)

If performance is an issue, you may want to consider the possibility of optimizing the code by using some *optimizer* like *numba*:

In [22]:
from numba import jit

@jit
def opt_factorial(n):     
    jn=1
    fact=1
    while jn <= n:
        fact=fact*jn
        jn=jn+1


    return fact

In [23]:
opt_factorial(20)

2432902008176640000

Evaluation of the performance of the optimized function:

In [24]:
timeit(opt_factorial(20))

155 ns ± 1.93 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


whereas the performance of the original not optimized (and not recursive) function was 

In [25]:
timeit(factorial(20))

1.3 μs ± 115 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In the case of factorial, a function also exists as part of the library *math*; such *math* functions are generally very efficient due to the fact that they are written in *C* and *compiled*:   

In [26]:
import math

math.factorial(20)

2432902008176640000

Here is its performance:

In [27]:
timeit(math.factorial(20))

199 ns ± 4.79 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


So, our *numba* optimized *opt_factorial* function is even more efficient than the *C-compile math.factorial* function! 

However...

In [28]:
opt_factorial(50)

-3258495067890909184

That is, $n!$ for $n$ relatively large is badly evaluated by the optimized function... That's definitely a problem having to do with *overflow* in the integers representation. One *quick* trick to solve the problem is to switch to float numbers representation (but then the result is not precise):

In [29]:
from numba import jit

@jit
def opt_factorial(n):     
    jn=1.
    fact=1.
    while jn <= n:
        fact=fact*jn
        jn=jn+1.

    return fact

In [30]:
int(opt_factorial(30.))

265252859812191032188804700045312

whereas the precise result is:

In [31]:
math.factorial(30)

265252859812191058636308480000000

So: it is possible to optimize functions by using the *numba* library, but care is required and the procedure is not that straightforward: a strict control of the type of the variables employed is generally necessary.   

### Functions returning more than one value:

In [32]:
def my_func(a,b):
    c=a*b
    return a,b,c

# Three ways to get results from my_func

v1,v2,v3=my_func(3,2)
print(v1,v2,v3)

# first and second output values are neglected
_,_,v3=my_func(4,5)
print(v3)

# values saved in a list
vl=my_func(4,5)
print(vl)

3 2 6
20
(4, 5, 20)


### *Starring* the arguments of a function

If the number of the arguments to a given function is not known at the time of the function definition, or it may change at the time the function is *invoked*, the variable specifying the argument can be *starred*. Here, the *my_sum* function returns the sum of its arguments: 

In [33]:
def my_sum(*val):
    s=0
    for iv in val:
        s=s+iv
    return s

In [34]:
my_sum(1,2,3)

6

In [35]:
my_sum(4,5)

9

Note that the following definition is correct (the *b* value is multiplied to the sum of the *val* values):

In [36]:
def my_sum(b,*val):
    s=0
    for iv in val:
        s=s+iv
    return s*b

In [37]:
my_sum(2,2,3,5)

20

This other version does not give any problem at the *time of definition*:

In [38]:
def my_sum(*val,b):
    s=0
    for iv in val:
        s=s+iv
    return s*b

... but it results in an error at *runtime*

In [39]:
my_sum(2,3,5,2)

TypeError: my_sum() missing 1 required keyword-only argument: 'b'

as the last value (2) is seen as a further element of the *tuple* *val*, and no value for b is provided...

Indeed, in the definition, *b* is seen as a *keyword* argument (for which no *default* value has been provided). In fact, the following call is perfectly *legal*:

In [40]:
my_sum(2,3,5, b=2)

20

Instead of using *starred* arguments, some code controlling the *type* of the arguments provided in input, can be inserted into the function itself. For instance:

In [41]:
def my_func(val, factor=2):
    
    if type(val) == list:
       result=[factor*ival for ival in val]
    else:
       result=factor*val
    
    return result

In [42]:
my_func(3,3)

9

In [43]:
my_func([2,3,5],3)

[6, 9, 15]

Note that things are much easier if numpy is used:

In [44]:
import numpy as np

def my_func(val, factor=2):
    return val*factor

x=np.array([2,3,5])
print(my_func(x))
print(my_func(5))

[ 4  6 10]
10


... but if *x* is a Python list, try to *explain* what's going on here...

In [45]:
x=[2,3,5]
my_func(x)

[2, 3, 5, 2, 3, 5]

### Lambda Functions (*Anonymous* functions)

Essentially, *lambda* functions are short, simple (one statement) functions with no name...

A *lambda* construct is of the type

```
lambda x: some simple algorithm involving x
```
where ``` x ``` is the argument of the function. 

A *lambda* function can be assigned to a variable, as in the following simple example:

In [46]:
f=lambda x: x**2

in this case *f* is a function that takes a number and returns its squared value. In fact:

In [47]:
type(f)

function

In [48]:
f(5)

25

A *lambda* function can take more than one argument:

In [49]:
f=lambda x,y: x*y

In [50]:
f(2,3)

6

#### Exercise: understand what the following function will do...

In [51]:
f = lambda ini, a: [ini+a[j] for j in range(len(a))]

In [52]:
f(2,[5,7,9])

[7, 9, 11]

The following function (*power*) gets a number (*pow*; default value: 2) and returns a function that takes a number and raises it to the power *pow*

In [53]:
def power(pow=2):
    f=lambda x: x**pow
    return f

*Guess* what the following code does...

In [54]:
f2=power()
f3=power(3)

x=[1,2,3,4,5]
y=[[ix, f2(ix), f3(ix)] for ix in x]

In [55]:
print(y)

[[1, 1, 1], [2, 4, 8], [3, 9, 27], [4, 16, 64], [5, 25, 125]]


If *x* is defined as a numpy array, we could write:

In [56]:
import numpy as np
x=np.array([1,2,3,4,5])
y=np.array([x, f2(x),f3(x)])

In [57]:
print(y)

[[  1   2   3   4   5]
 [  1   4   9  16  25]
 [  1   8  27  64 125]]


### Exercise:

Write a function that takes several file names as arguments, each file containing a variable column number of floating point data (and a fixed number of rows), and merges them into a unique file containing all of the columns of the original files; optionally, we may want the data to be sorted according to a specific column of the merged file.

In [58]:
import numpy as np

def merge(*files, path='./', out_file='merged.dat', out=False, sorting=-1):
        
    data=np.array([])
    n_file=len(files)
    ncol=0
    
    for i_file in files:
        iname=path+i_file
        idata=np.loadtxt(iname)
        icol=idata.ndim
        ncol=ncol+icol
        if icol == 1:
           data=np.append(data, idata)
        else:
           for jcol in range(icol):
               ix=idata[:,jcol]
               data=np.append(data, ix)
        
    len_data=data.size
    nrow=int(len(data)/ncol)
    
    data_final=data.reshape(nrow, ncol)
    
    if sorting != -1:
       icol=sorting
       col=data_final[icol]
       pos_col=np.argsort(col)
       for ic in range(ncol):
           data_final[ic]=data_final[ic, pos_col]
       
    data_for_out=np.transpose(data_final.reshape(ncol, nrow))
    
    out_name=path+out_file
    np.savetxt(out_name, data_for_out, fmt='%7.3f')
    
    if out:    
       return data_final

In [59]:
data=merge('file_1.dat', 'file_2.dat', 'file_3.dat', 'file_4.dat', path='./data_files/', out=True, sorting=3)

In [60]:
print(data)

[[ 5.  4.  3.  2.  1.]
 [10.  9.  8.  7.  6.]
 [15. 14. 13. 12. 11.]
 [21. 22. 23. 24. 25.]
 [20. 19. 18. 17. 16.]]
